### ISSUE TITLE
Resolution error when dependency in node_module has file extension

### ISSUE THREAD

**Issue by fpaglia-rbi** [FormidableLabs/serverless-jetpack#361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Bug report

Hello,

We started getting a weird resolution error after upgrading a library in one of our projects. Jetpack is trying to resolve an import from a dependency with its extension twice (eg: `.js.js`).

```markdown
[serverless-jetpack] Packaging 33 functions, 0 services, and 0 layers with concurrency 2
[serverless-jetpack] Packaged function (trace mode): .serverless/remove-dupes.zip (3.10s)
Environment: linux, node 20.11.0, framework 3.38.0 (local), plugin 7.2.3, SDK 4.5.1
Credentials: Local, "xxx.xxx.xx.xx" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: Encountered resolution error in /home/circleci/project/x/.build/node_modules/@graphql-tools/utils/esm/index.js for ./Interfaces.js: Error: Cannot find export './esm/Interfaces.js.js' in module './Interfaces.js' from '/home/circleci/project/x/.build/node_modules/@graphql-tools/utils/esm'
    at /home/circleci/project/x/node_modules/trace-deps/lib/trace.js:419:13
    at async Promise.all (index 0)
    at async traceFile (/home/circleci/project/x/node_modules/trace-deps/lib/trace.js:534:19)
    at async _recurseDeps (/home/circleci/project/x/node_modules/trace-deps/lib/trace.js:175:22)
    at async traceFile (/home/circleci/project/x/node_modules/trace-deps/lib/trace.js:565:20)
    at async _recurseDeps (/home/circleci/project/x/node_modules/trace-deps/lib/trace.js:175:22)
    at async traceFile (/home/circleci/project/x/node_modules/trace-deps/lib/trace.js:565:20)
    at async _recurseDeps (/home/circleci/project/x/node_modules/trace-deps/lib/trace.js:175:22)
    at async traceFile (/home/circleci/project/x/node_modules/trace-deps/lib/trace.js:565:20)
    at async _recurseDeps (/home/circleci/project/x/node_modules/trace-deps/lib/trace.js:175:22)
```

The actual file that it's trying to resolve (`@graphql-tools/utils`), happens for both cjs and esm variations:

```esm/index.js
export * from './loaders.js';
...
export * from './Interfaces.js';
```

I'd appreciate any help! Thanks in advance :)

**Comment by ryan-roemer** [comment]
Which version of `serverless-jetpack` and `trace-deps` are you on?

**Comment by fpaglia-rbi** [comment]
`serverless-jetpack` on `0.11.2`, `trace-deps` on `0.4.2`

**Comment by ryan-roemer** [comment]
Can you update trace-deps to `trace-deps@4.11` and see if that works?

If not, can you then manually update to `trace-deps@0.5.2` (even though that's not presently semver compliant) and see if that works?

Thanks!

**Comment by fpaglia-rbi** [comment]
Thanks a lot, using `trace-deps@0.5.2` solved the issue!
